apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2  # Increased the replicas for better fault tolerance
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: <ECR REPO>/doctor-office-frontend
          resources:
            requests:
              cpu: "0.1"  
              memory: "100Mi"
            limits:
              cpu: "0.3"  # Balanced  the CPU usage to avoid overcommitment
              memory: "200Mi"  # Increased the memory limit for burst traffic
          ports:
            - containerPort: 3000
          readinessProbe:  # Added readiness probe for better health monitoring
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:  # Added liveness probe to ensure container health
            httpGet:
              path: "/health"
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
