apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
stringData:
  AWS_REGION: us-east-1 
  AWS_ACCESS_KEY_ID: <ACCESS-KEY>
  AWS_SECRET_ACCESS_KEY: <SECRET-KEY>
  DYNAMODB_TABLE_NAME: Appointments
