apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 2  # Increased the replicas for better fault tolerance
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <ECR REPO>/doctor-office-backend
          resources:
            requests:
              cpu: "0.3"
              memory: "256Mi"  # Increased memory requests for stability
            limits:
              cpu: "0.6"
              memory: "512Mi"  # Increased the limits to handle heavy loads
          ports:
            - containerPort: 5000
          readinessProbe:  # # Added readiness probe for better health monitoring
            httpGet:
              path: "/health"
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:  # Added liveness probe to ensure container health
            httpGet:
              path: "/health"
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_REGION
            - name: DYNAMODB_TABLE_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: DYNAMODB_TABLE_NAME